#!/usr/bin/env sh
set -e

CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

if [ -n "$CHANGED_FILES" ]; then
  npx --no-install eslint --max-warnings 0 $CHANGED_FILES
fi

npx --no-install lint-staged
